name: Запуск Minecraft

on: [workflow_dispatch]

jobs:
  build-and-run-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download and Run Server (Direct Link)
        run: |
          mkdir server
          cd server
          # Используем curl, чтобы найти прямую ссылку на .jar и скачать её
          curl -sL https://mcserverjars.com/purpur/1.21.4 | grep -o 'https://.*\.jar' | head -1 | wget -i -
          echo "eula=true" > eula.txt
          java -Xmx1024M -Xms1024M -jar server.jar nogui
