name: Запуск Minecraft

# Этот workflow будет запускаться при каждой загрузке файлов
on: [push]

jobs:
  build-and-run-server:
    runs-on: ubuntu-latest # Запускаем на бесплатном сервере с Ubuntu

    steps:
      # Шаг 1: Получить файлы из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Установить Java, так как на сервере ее нет по умолчанию
      - name:
