name: Запуск Minecraft

on: [workflow_dispatch]

jobs:
  build-and-run-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download and Run Server
        run: |
          # Создаем папку для сервера и переходим в неё
          mkdir server
          cd server

          # Скачиваем файл напрямую по рабочей ссылке
          wget https://api.purpurmc.org/v2/purpur/1.21.4/2416/download -O server.jar

          # Принимаем лицензию и запускаем сервер
          echo "eula=true" > eula.txt
          java -Xmx1024M -Xms1024M -jar server.jar nogui
